!==============================================================================!
!                                   SKETCH-N                                   !
!  Nodal Neutron Diffusion Code for Solving Steady-State and Kinetics Problems !
!              Version 1.0 (c) Slava 2000 e-mail: na.vzimin@na-net.ornl.gov    !
!      Date & Time of Calculation :  6 June     2019  11:30:12 am              !
!==============================================================================!
WARNING:
 Could not find identifier XS_MODL_TYPE in the FILE_INPUT, set set macro cross s
 ection model to POLYNOM
Warning:
 Could not find identifier XS_ADF_DATA in the FILE_INPUT assembly  discontinuity
  factors set to 1
WARNING:
 Could not find identifier XSP_POL_COEF in the FILE_INPUTset XS polynomial coeff
 icients to 0
WARNING:
 Could not find identifier XS_FEED_INIT in the FILE_INPUT    set fdback0(N_FEEDB
 ACK) = 1
WARNING:
 Could not find identifier XS_CROD_COEF in the FILE_INPUTset control rod differe
 ntial XS  to 0.
WARNING:
 Could not find identifier XS_CROD_CUSP in the FILE_INPUT, set homogenization of
  XS for the partial rodded nodes to the flux-weighting method
WARNING:
 Could not find identifier XS_POWR_COOL in the FILE_INPUT set direct coolant hea
 ting 0
Warning:
 Could not find identifier GMT_MSH_NV in the FILE_INPUT,  HEXagonal spatial mesh
  is not given,  Set NV to NX (OK for Symmetric Core
WARNING:
 Could not find identifier GMT_NUM_CORE in the FILE_INPUT,  core geometry is def
 ined by the fission materials
WARNING:
 Could not find identifier CRD_COR_LOAD in the FILE_INPUT, types of the control 
 rods set to 1
WARNING:
 Could not find identifier CRD_MAT_COMP in the FILE_INPUT, material compositions
  of the control rods set to 1
WARNING:
 Could not find identifier CRD_LOCATION in the FILE_INPUT, set locations of the 
 control rods  to 0
WARNING:
 Could not find identifier CRD_POSITION in the FILE_INPUT, set positions of the 
 control rods  to 0
WARNING:
 Could not find identifier CRD_H_ROD_EL in the FILE_INPUT, set heights of the co
 ntrol rod elements  to 0
WARNING:
 Could not find identifier CRD_BNK_INDX the FILE_INPUT, no information on CR ban
 k is available
